
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.minijava;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int LBRACKET = 12;
  public static final int MULT = 5;
  public static final int INTEGER = 19;
  public static final int LPAREN = 10;
  public static final int INT = 22;
  public static final int LESS = 6;
  public static final int MINUS = 9;
  public static final int STATIC = 34;
  public static final int RPAREN = 11;
  public static final int NOT = 8;
  public static final int LCURL = 14;
  public static final int SEMICOLON = 16;
  public static final int COMMA = 17;
  public static final int CLASS = 35;
  public static final int BAND = 7;
  public static final int PLUS = 3;
  public static final int MAIN = 37;
  public static final int IF = 27;
  public static final int THIS = 32;
  public static final int DOT = 29;
  public static final int EOF = 0;
  public static final int BOOLEAN = 23;
  public static final int RETURN = 38;
  public static final int RBRACKET = 13;
  public static final int TRUE = 20;
  public static final int NEW = 31;
  public static final int error = 1;
  public static final int BECOMES = 4;
  public static final int VOID = 25;
  public static final int RCURL = 15;
  public static final int ELSE = 28;
  public static final int WHILE = 26;
  public static final int PUBLIC = 33;
  public static final int EXTENDS = 36;
  public static final int STRING = 24;
  public static final int FALSE = 21;
  public static final int PRINT = 2;
  public static final int LENGTH = 30;
  public static final int IDENTIFIER = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PRINT",
  "PLUS",
  "BECOMES",
  "MULT",
  "LESS",
  "BAND",
  "NOT",
  "MINUS",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "LCURL",
  "RCURL",
  "SEMICOLON",
  "COMMA",
  "IDENTIFIER",
  "INTEGER",
  "TRUE",
  "FALSE",
  "INT",
  "BOOLEAN",
  "STRING",
  "VOID",
  "WHILE",
  "IF",
  "ELSE",
  "DOT",
  "LENGTH",
  "NEW",
  "THIS",
  "PUBLIC",
  "STATIC",
  "CLASS",
  "EXTENDS",
  "MAIN",
  "RETURN"
  };
}

